sudo: required

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env: SCIDB_VER=16.9 SHIM_VER=16.9

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --name scidb
    --detach
    --volume /dev/shm
    --tmpfs /dev/shm:exec
    --publish 8080:8080
    --publish 8083:8083
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 1; done

install:
  - docker exec scidb bash -c "
    ln --symbolic /opt/scidb/${SCIDB_VER}/lib/libscidbclient.so /lib/;
    wget --no-verbose https://github.com/Paradigm4/shim/archive/v${SHIM_VER}.tar.gz;
    tar --extract --gzip --file /shim-${SHIM_VER}.tar.gz;
    make --directory /shim-${SHIM_VER} service;
    service shimsvc restart"
  - pip install --upgrade -r requirements.txt

script:
  - pep8 .
  - pytest
  - pip install .

after_failure:
  - docker logs scidb
