sudo: required

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env: SCIDB_VER=16.9

services: docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --detach
    --volume /dev/shm
    --tmpfs /dev/shm:exec
    --publish 8080:8080
    rvernica/scidb:${SCIDB_VER}
  - docker ps --all

install:
  - pip install --only-binary=scipy requests numpy pep8 pytest

script:
  - pep8 scidbpy
  - pytest --doctest-modules
