sudo: required

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env: SCIDB_VER=16.9

services: docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --name scidb
    --detach
    --volume /dev/shm
    --tmpfs /dev/shm:exec
    --publish 8080:8080
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 1; done

install:
  - pip install --only-binary=scipy
    enum34
    numpy
    pandas
    pep8
    pytest
    requests

script:
  - pep8 scidbpy
  - pytest --doctest-modules

after_failure:
  - docker logs scidb
